[package]
name = "blog-ui"
version = "0.0.1"
edition = "2021"
license = "MIT"


[dependencies]
log = "0.4"
async-trait = "0.1"

futures = { version = "0.3", features = ["std"], default-features = false }

reqwest = { version = "0.11.13", features = ["json"] }

yew = { git = "https://github.com/yewstack/yew", branch = "master", features = ["ssr"] }
yew-router = { git = "https://github.com/yewstack/yew", branch = "master" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

urlencoding = "2.1"


[target.'cfg(target_arch = "wasm32")'.dependencies]
yew-hooks = { git = "https://github.com/tikitko/yew-hooks.git", branch = "main"  }

gloo = "0.8"

wasm-bindgen-futures = "0.4"
wasm-bindgen = "0.2"
wasm-cookies = "0.2"
wasm-logger = "0.2"

web-sys = { version = "0.3", features = ["HtmlDocument","console","Document","HtmlElement","MouseEvent","DomRect","ScrollToOptions","ScrollBehavior","Element","MouseEvent","CssStyleDeclaration","MutationObserver","MutationObserverInit","Node"] }


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.29.0", features = ["full"] }
warp = "0.3"
clap = { version = "4", features = ["derive"] }
bytes = "1.4"


[[bin]]
name = "blog_ui_hydrate"
required-features = ["hydration"]

[[bin]]
name = "blog_ui_server"
required-features = ["ssr"]

[features]
ssr = ["yew/ssr"]
hydration = ["yew/hydration"]


[profile.release]
# less code to include into binary
panic = 'abort'
# optimization over all codebase ( better optimization, slower build )
codegen-units = 1
# optimization for size ( more aggressive )
opt-level = 'z'
# optimization for size
# opt-level = 's'
# link time optimization using using whole-program analysis
lto = true