[package]
name = "blog"
version = "0.0.1"
edition = "2021"
license = "MIT"


[dependencies]
log = "0.4"

yew = { git = "https://github.com/yewstack/yew", branch = "master", features = ["csr"] }
yew-router = { git = "https://github.com/yewstack/yew", branch = "master" }

wasm-bindgen-futures = "0.4"
wasm-bindgen = "0.2"
wasm-cookies = { version = "0.2" }
wasm-logger = "0.2"

web-sys = { version = "0.3", features = ["HtmlDocument","console","Document","HtmlElement","MouseEvent","DomRect","ScrollToOptions","ScrollBehavior","Element","MouseEvent","CssStyleDeclaration","MutationObserver","MutationObserverInit","Node"] }

gloo = "0.8"
gloo-net = "0.2"

serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }


[profile.release]
# less code to include into binary
panic = 'abort'
# optimization over all codebase ( better optimization, slower build )
codegen-units = 1
# optimization for size ( more aggressive )
opt-level = 'z'
# optimization for size
# opt-level = 's'
# link time optimization using using whole-program analysis
lto = true