[package]
name = "blog"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
instant = { version = "0.1", features = ["wasm-bindgen"] }
lipsum = "0.9.0"
log = "0.4"
getrandom = { version = "0.2", features = ["js"] }
rand = { version = "0.8", features = ["small_rng"] }
wasm-logger = "0.2"
yew = { git = "https://github.com/yewstack/yew", branch = "master", features = ["csr"] }
yew-router = { git = "https://github.com/yewstack/yew", branch = "master" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
once_cell = "1"
gloo = "0.8"
gloo-net = "0.2"
wasm-bindgen-futures = "0.4"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["HtmlDocument","console","Document","HtmlElement","MouseEvent","DomRect","ScrollToOptions","ScrollBehavior","Element","MouseEvent"] }
wasm-cookies = { version = "0.2" }

[profile.release]
# less code to include into binary
panic = 'abort'
# optimization over all codebase ( better optimization, slower build )
codegen-units = 1
# optimization for size ( more aggressive )
opt-level = 'z'
# optimization for size
# opt-level = 's'
# link time optimization using using whole-program analysis
lto = true