[package]
name = "blog-ui"
version = "0.0.1"
edition = "2021"
license = "MIT"


[dependencies]
log = "0.4"
async-trait = "0.1"

# yew = { git = "https://github.com/yewstack/yew", branch = "master" }
# yew-router = { git = "https://github.com/yewstack/yew", branch = "master" }
yew = "0.20"
yew-router = "0.17"
yew-hooks = "0.2"

wasm-bindgen-futures = "0.4"
wasm-bindgen = "0.2"
wasm-cookies = "0.2"
wasm-logger = "0.2"

web-sys = { version = "0.3", features = ["HtmlDocument","console","Document","HtmlElement","MouseEvent","DomRect","ScrollToOptions","ScrollBehavior","Element","MouseEvent","CssStyleDeclaration","MutationObserver","MutationObserverInit","Node"] }

gloo = "0.8"
gloo-net = "0.2"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

urlencoding = "2.1"


[profile.release]
# less code to include into binary
panic = 'abort'
# optimization over all codebase ( better optimization, slower build )
codegen-units = 1
# optimization for size ( more aggressive )
opt-level = 'z'
# optimization for size
# opt-level = 's'
# link time optimization using using whole-program analysis
lto = true

[[bin]]
name = "blog_ui"
required-features = ["yew/csr"]