name: Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: jetli/trunk-action@v0.4.0
    - name: Target Add `wasm32-unknown-unknown`
      run: rustup target add wasm32-unknown-unknown
    - name: Trunk Build
      run: trunk build --release
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
